[[redirects]]
  from = "/index2.html"
  to = "https://mcloud2.to"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify",Referer="https://mcloud2.to/"}